public class get_file {
    public String get_file(int number){
        if(number==1)
            return "img/mei1.jpg";
        else if(number==2)
            return "img/mei2.jpg";
        else if(number==3)
            return "img/mei3.jpg";
        else if(number==4)
            return "img/mei4.jpg";
        else if(number==5)
            return "img/mei5.jpg";
        else if(number==6)
            return "img/mei6.jpg";
        else if(number==7)
            return "img/mei7.jpg";
        else if(number==8)
            return "img/mei8.jpg";
        else if(number==9)
            return "img/mei9.jpg";
        else if(number==10)
            return "img/mei10.jpg";
        else if(number==11)
            return "img/mei11.jpg";
        else if(number==12)
            return "img/mei12.jpg";
        else if(number==13)
            return "img/mei13.jpg";

        else if(number==14)
            return "img/hei1.jpg";
        else if(number==15)
            return "img/hei2.jpg";
        else if(number==16)
            return "img/hei3.jpg";
        else if(number==17)
            return "img/hei4.jpg";
        else if(number==18)
            return "img/hei5.jpg";
        else if(number==19)
            return "img/hei6.jpg";
        else if(number==20)
            return "img/hei7.jpg";
        else if(number==21)
            return "img/hei8.jpg";
        else if(number==22)
            return "img/hei9.jpg";
        else if(number==23)
            return "img/hei10.jpg";
        else if(number==24)
            return "img/hei11.jpg";
        else if(number==25)
            return "img/hei12.jpg";
        else if(number==26)
            return "img/hei13.jpg";

        else if(number==27)
            return "img/hong1.jpg";
        else if(number==28)
            return "img/hong2.jpg";
        else if(number==29)
            return "img/hong3.jpg";
        else if(number==30)
            return "img/hong4.jpg";
        else if(number==31)
            return "img/hong5.jpg";
        else if(number==32)
            return "img/hong6.jpg";
        else if(number==33)
            return "img/hong7.jpg";
        else if(number==34)
            return "img/hong8.jpg";
        else if(number==35)
            return "img/hong9.jpg";
        else if(number==36)
            return "img/hong10.jpg";
        else if(number==37)
            return "img/hong11.jpg";
        else if(number==38)
            return "img/hong12.jpg";
        else if(number==39)
            return "img/hong13.jpg";

        else if(number==40)
            return "img/fang1.jpg";
        else if(number==41)
            return "img/fang2.jpg";
        else if(number==42)
            return "img/fang3.jpg";
        else if(number==43)
            return "img/fang4.jpg";
        else if(number==44)
            return "img/fang5.jpg";
        else if(number==45)
            return "img/fang6.jpg";
        else if(number==46)
            return "img/fang7.jpg";
        else if(number==47)
            return "img/fang8.jpg";
        else if(number==48)
            return "img/fang9.jpg";
        else if(number==49)
            return "img/fang10.jpg";
        else if(number==50)
            return "img/fang11.jpg";
        else if(number==51)
            return "img/fang12.jpg";
        else if(number==52)
            return "img/fang13.jpg";

        else
            return "ERROR";
    }
}
